### PR TITLE
Fix Issue #12 + Add Issue #4 + cleanup repo

### LINKED ISSUE #12: [Bug]: everyNDays(days: 5) doesn't work
### What happened?

Create event for date 2024-02-19 15:30 every 5 days.
whereOccurresOn(Carbon::make('2024-02-29'))->get(); returns empty, but it should repeat event in this date

### How to reproduce the bug

Create event for date 2024-02-19 15:30 every 5 days.

### Package Version

0.5.1

### PHP Version

8.2

### Laravel Version

10.43

### Which operating systems does with happen with?

Linux

### Notes

Also it doesn't work for events that have duration more than one day, for example, start date 2024-02-19 15:30, end date 2024-02-22 17:30

### PR DESCRIPTION
**Pull request by EriBloo**
Hi,
this pull fixes [Issue #12](https://github.com/mohammedmanssour/laravel-recurring-models/issues/12). Additionally I formated repository, fixed phpstan and upgraded it to level 6 and fixed tests.

### CODE REVIEW

**Comment by EriBloo** [comment]
I added 2 more commits:
- one fixes typo `repeatitions` to `repetitions` in PendingRepeat
- second moves `start_at` initialization to PendingRepeat and makes it consistent across different Repeat classes (EveryNDaysRepeat skipped first repetition, others didn't)

**Comment by EriBloo** [comment]
I also added [this feature](https://github.com/mohammedmanssour/laravel-recurring-models/issues/4)

**Comment by Sergiobop** [comment]
Nice work @EriBloo 
I hope @mohammedmanssour can see this one and update the repo to Laravel 11 too.

Thanks

**Comment by mohammedmanssour** [comment]
Thanks @EriBloo 
I'll be looking into this one soon

**Comment by Sergiobop** [comment]
Hi @mohammedmanssour did you have the chance to look into this?

I also need to upgrade some projects to Laravel 11 and the package is the last thing blocking me https://github.com/mohammedmanssour/laravel-recurring-models/issues/14

Thanks

**Pull request merged**
